
trigger:
- development


pool:
  name: MyAgentPool
  demands:
   -  mvn
  
 
steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      testResultsFiles: '**surefire-reports/TEST-*.xml'
      javaHomeOption: JDKVersion
      mavenVersionOption: Default
  
  - task: CopyFiles@2
    inputs:
      Contents: '**/target/*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      publishLocation: 'pipeline'
      artifact: 'my-artifact'




    
    


