name: First Workflow - Training_1st_Dec_2025

on: 
 push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Print
     run: echo "Build"
     
 test:
  runs-on: windows-latest
   steps:
   - name: Print
     run: echo "Test"
   
 deploy:
  runs-on: ubuntu-latest
   steps:
   - name: Print
     run: echo "Deploy"
   
 
