name: First Workflow - Training_1st_Dec_2025

on: 
 push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v6.0.0
   - name: Setup Java JDK
     uses: actions/setup-java@v5.0.0
     with:
      java-version: '17'
      distribution: microsoft

   - name: Build with Maven
     run: |
      mvn -B clean install --no-transfer-progress
      mkdir staging && cp target/*.jar staging

   - name: Upload a Build artifact
     uses: actions/upload-artifact@v5.0.0
     with:
      name: Package
      path: staging
      
      
      
      
     
     
 
